### ISSUE TITLE
Resume Link not working

### ISSUE THREAD

**Issue by Raeskaa** [kunal-kushwaha/kunal-kushwaha#18]
The portfolio website linked to your name ( **Kunal**) gives a 404 error when clicked at your **Resume** section
![image](https://user-images.githubusercontent.com/84667136/151649744-7aa415c2-d429-4366-b9c6-6497a1d7a798.png)
![image](https://user-images.githubusercontent.com/84667136/151649693-ea53566a-972f-4297-8c35-01a6aa8b3a51.png)
![image](https://user-images.githubusercontent.com/84667136/151649702-dc38839e-de34-4859-9f97-f241caf80053.png)

It'd be great if you updated it!

**Comment by kunal-kushwaha** [comment]
Thank You
